import os
import json
import argparse
import yaml
import numpy as np
import torch
import matplotlib.pyplot as plt

from dataset.FaultSeg3D_Dataset import FaultSeg3D2DSlices
from models.factory import build_model
from utils.seed import set_seed

# Model list: (display_name, config_path, checkpoint_path)
MODEL_RUNS = [
    ("UNet", "configs/unet.yaml", "runs/unet/best.pt"),
    ("ResNet50_UNet", "configs/resnet50_unet.yaml", "runs/resnet50_unet/best.pt"),
    ("TransUNet", "configs/transunet.yaml", "runs/transunet/best.pt"),
    ("TransAttUNet", "configs/transattunet.yaml", "runs/transattunet/best.pt"),
    ("SwinUNet", "configs/swinunet.yaml", "runs/swinunet/best.pt"),
    ("TransDeepLab", "configs/transdeeplab.yaml", "runs/transdeeplab/best.pt"),
    ("MaxViTUNet", "configs/maxvitunet.yaml", "runs/maxvitunet/best.pt"),
    ("ConvNeXtUNet", "configs/convnextunet.yaml", "runs/convnextunet/best.pt"),
    ("SegFormer", "configs/segformer.yaml", "runs/segformer/best.pt"),
]


def get_device(pref: str = ""):
    pref = (pref or "").lower().strip()
    if pref in ["cuda", "cpu", "mps"]:
        return torch.device(pref)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if getattr(torch.backends, "mps", None) is not None and torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def split_val_test_ids(val_split_dir: str, val_count: int, test_count: int):
    """
    Same as train_faultseg3d.py:
      - sort filenames
      - first val_count -> val
      - next test_count -> test
    """
    seis_dir = os.path.join(val_split_dir, "seis")
    ids = sorted(
        [
            os.path.splitext(f)[0]
            for f in os.listdir(seis_dir)
            if f.endswith(".dat") and (not f.startswith("."))
        ]
    )
    assert len(ids) >= val_count + test_count, f"Need >= {val_count+test_count} volumes, got {len(ids)}"
    val_ids = ids[:val_count]
    test_ids = ids[val_count: val_count + test_count]
    return val_ids, test_ids


def safe_load_checkpoint(model: torch.nn.Module, ckpt_path: str, device: torch.device, disp_name: str = ""):
    """
    Load checkpoint with strict=False to tolerate minor key differences.
    """
    state = torch.load(ckpt_path, map_location=device)
    sd = state["model"] if isinstance(state, dict) and "model" in state else state

    incompat = model.load_state_dict(sd, strict=False)
    missing = list(incompat.missing_keys) if hasattr(incompat, "missing_keys") else []
    unexpected = list(incompat.unexpected_keys) if hasattr(incompat, "unexpected_keys") else []

    if missing or unexpected:
        name = disp_name or ckpt_path
        print(f"[WARN] load_state_dict(strict=False) for {name}")
        if unexpected:
            print("  unexpected keys (show up to 12):", unexpected[:12])
        if missing:
            print("  missing keys (show up to 12):", missing[:12])

    return model


def load_test_ids_with_train_logic(data_root: str, cfg_ref: dict, split_json: str = ""):
    """
    Priority:
      1) If split_json exists -> use its test_ids (exactly same as training)
      2) Else -> deterministic split by filenames (same as training code)
    """
    val_dir = os.path.join(data_root, cfg_ref["data"]["val_split"])

    if split_json and os.path.exists(split_json):
        with open(split_json, "r", encoding="utf-8") as f:
            obj = json.load(f)
        test_ids = obj.get("test_ids", None)
        if not test_ids:
            raise ValueError(f"{split_json} exists but has no 'test_ids'. Keys={list(obj.keys())}")
        print(f"[INFO] Using test_ids from split_json: {split_json} (N={len(test_ids)})")
        return val_dir, test_ids

    # fallback
    val_ids, test_ids = split_val_test_ids(
        val_dir,
        int(cfg_ref["data"]["val_count"]),
        int(cfg_ref["data"]["test_count"]),
    )
    print("[INFO] split_json not found. Fallback to deterministic split_val_test_ids().")
    print(f"[INFO] val_ids={len(val_ids)}, test_ids={len(test_ids)}")
    return val_dir, test_ids


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data_root", type=str, default="./data/wangjing")
    ap.add_argument("--device", type=str, default="")
    ap.add_argument("--out", type=str, default="runs/qualitative_grid_test.png")
    ap.add_argument("--axis", type=int, default=0, help="0/1/2")
    ap.add_argument("--slice", type=int, default=-1, help="-1 means middle slice")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument(
        "--split_json",
        type=str,
        default="runs/unet/val_test_split.json",
        help="Path to val_test_split.json generated by training (to ensure same test_ids).",
    )
    ap.add_argument(
        "--ref_config",
        type=str,
        default="configs/unet.yaml",
        help="Reference config to read shared dataset settings.",
    )
    args = ap.parse_args()

    set_seed(args.seed, deterministic=True)
    device = get_device(args.device)
    print(f"[INFO] Device: {device}")

    # Reference config
    with open(args.ref_config, "r", encoding="utf-8") as f:
        cfg_ref = yaml.safe_load(f)

    # Load test_ids exactly like training
    val_dir, test_ids = load_test_ids_with_train_logic(args.data_root, cfg_ref, split_json=args.split_json)

    # Fixed samples: (volume_id, axis, slice_idx) for each test volume
    D = int(cfg_ref["data"]["vol_shape"][args.axis])
    sidx = (D // 2) if args.slice < 0 else int(args.slice)
    fixed = [(vid, int(args.axis), int(sidx)) for vid in test_ids]
    print(f"[INFO] Fixed samples (N={len(fixed)}): {fixed}")

    # Dataset: no augmentation, fixed sampling
    ds = FaultSeg3D2DSlices(
        split_dir=val_dir,
        ids=test_ids,
        vol_shape=tuple(cfg_ref["data"]["vol_shape"]),
        axes=cfg_ref["data"]["axes"],
        img_size=int(cfg_ref["data"]["img_size"]),
        is_train=False,
        mode="eval_fixed",
        fixed_samples=fixed,
        aug_p=0.0,
        seed=args.seed,
    )

    # Load all models
    models = []
    for disp_name, cfg_path, ckpt_path in MODEL_RUNS:
        with open(cfg_path, "r", encoding="utf-8") as f:
            c = yaml.safe_load(f)
        mcfg = c["model"]

        model = build_model(
            mcfg["name"],
            n_channels=mcfg.get("n_channels", 1),
            n_classes=mcfg.get("n_classes", 1),
            pretrained=bool(mcfg.get("pretrained", False)),
            **(mcfg.get("kwargs", {}) or {}),
        ).to(device)

        if not os.path.exists(ckpt_path):
            raise FileNotFoundError(f"Checkpoint not found: {ckpt_path}. Train first.")

        model = safe_load_checkpoint(model, ckpt_path, device, disp_name=disp_name)
        model.eval()
        models.append((disp_name, model))

    # Grid: rows = test volumes, cols = Seismic + GT + each model
    rows = len(ds)
    cols = 2 + len(models)
    fig, ax_grid = plt.subplots(rows, cols, figsize=(3.2 * cols, 3.0 * rows))
    if rows == 1:
        ax_grid = np.expand_dims(ax_grid, 0)

    vmin, vmax = 0.0, 100.0
    last_im = None

    for r in range(rows):
        img, mask, meta = ds[r]
        img_b = img.unsqueeze(0).to(device)

        # Seismic grayscale: de-normalize from [-1,1] to [0,1]
        img_vis = (img * 0.5 + 0.5).clamp(0, 1).squeeze(0).cpu().numpy()
        ax = ax_grid[r, 0]
        ax.imshow(img_vis, cmap="gray")
        ax.set_axis_off()
        if r == 0:
            ax.set_title("Seismic")

        # GT heatmap: 0..100
        gt = (mask.squeeze(0).cpu().numpy() * 100.0)
        ax = ax_grid[r, 1]
        last_im = ax.imshow(gt, cmap="jet", vmin=vmin, vmax=vmax)
        ax.set_axis_off()
        if r == 0:
            ax.set_title("GT")

        # Predictions
        c = 2
        for name, model in models:
            with torch.no_grad():
                logits = model(img_b)  # expected (B,1,H,W)
                prob = torch.sigmoid(logits).squeeze().detach().cpu().numpy() * 100.0
            ax = ax_grid[r, c]
            ax.imshow(prob, cmap="jet", vmin=vmin, vmax=vmax)
            ax.set_axis_off()
            if r == 0:
                ax.set_title(name)
            c += 1

    fig.subplots_adjust(right=0.92, wspace=0.02, hspace=0.02)
    cax = fig.add_axes([0.94, 0.15, 0.015, 0.7])
    fig.colorbar(last_im, cax=cax)

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    fig.savefig(args.out, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"[INFO] Saved: {args.out}")


if __name__ == "__main__":
    main()